### ISSUE TITLE
There are no visible error tooltips when submitting through http://hermes-dev.lco.gtn/

### ISSUE THREAD

**Issue by jchate6** [LCOGT/hermes-frontend#10]
The submit button is grayed out, and I don't see any issues.

**Comment by jchate6** [comment]
This is only true when "logged in". (see issue[ #10](https://github.com/LCOGT/hermes/issues/10) in Hermes).
Seems to work fine with Guest.

**Comment by jnation3406** [comment]
This should have been fixed with the last Pr
