### ISSUE TITLE
I have a series of GCN.classic.text options for hermes.guest that are not visible when logged in.

### ISSUE THREAD

**Issue by jchate6** [LCOGT/hermes-frontend#11]
Not the biggest of deals, I'm just not sure we need these visible to anyone?
I'm also not sure why, if they are public, I don't see them when logged in.

**Comment by jnation3406** [comment]
Logging in currently pulls what your logged in account can see.  I guess  I need to merge the two so you get all the topics in the database with read privileges, and then add in the write privileges according to the logged in user.

**Comment by jnation3406** [comment]
I believe this was fixed with the last merged PR - public / readable topics should now be the same set for both logged in or non-logged in users
