### ISSUE TITLE
Display Original GCN message without any formatting

### ISSUE THREAD

**Issue by jchate6** [LCOGT/hermes-frontend#31]
In the "Show JSON" modal we could have a "display raw message" option or something so show everything that was in a GCN.

**Comment by jnation3406** [comment]
For GCN messages from gcn classic over kafka, the raw message is just the message_text. It is already shown.

**Comment by jchate6** [comment]
OK, so that's why we couldn't see the updated schema? Because it was not classic?

**Comment by jnation3406** [comment]
yeah I am guessing it doesnt have an updated schema yet (or ever?)
